---
- block:

    - name: load {{ ansible_architecture }} vars
      include_vars: "vars/{{ ansible_architecture }}.yml"

    - name: load {{ ansible_system }} vars
      include_vars: "vars/{{ ansible_system }}.yml"

    - name: load {{ ansible_system }}-{{ ansible_architecture }} vars
      include_vars: "vars/{{ ansible_system }}-{{ ansible_architecture }}.yml"

    - name: run role
      include_role:
        name: rgibert.single_binary_service

  tags:
    - prometheus_pihole_exporter
